title: Mikhail Ushakov
description:  My CV
domain: www.mikhirurg.nl
url: https://www.mikhirurg.nl
baseurl: ""
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
