title: Mikahil Ushakov
description:  My CV
domain: mikhirurg.github.io
url: https://mikhirurg.github.io/
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
